### PR TITLE
Add docs for SGX attestation process and cert chain

### PR DESCRIPTION
**Pull request by lkatalin**
I copied the docs over from `enarx/docs/attestation/intel/sgx` based on this [conversation](https://chat.enarx.dev/channel/development?msg=xDjAYPrQo3Scox4Wn). However, I think these same docs should also go into our `enarx-keep` as well. Thoughts?

Resolves # 915 from the sprint board (will have to close manually).

Closes https://github.com/enarx/enarx/issues/915

### CODE REVIEW

**Review by npmccallum — CHANGES_REQUESTED** [review]
Please add a GitHub Actions workflow which generates the png files to check if they have changed (and fail if they have). We do [something similar here](https://github.com/enarx/sgx/blob/master/.github/workflows/lint.yml#L36-L47).

**Comment by lkatalin** [comment]
@npmccallum Would it be adequate to translate [this test](https://github.com/enarx/enarx/blob/master/docs/Makefile.toml#L56) to a GitHub Action? It tests whether the commit timestamp of the png is newer than that of the diagram file. According to this [conversation](https://chat.enarx.dev/channel/infrastructure?msg=xJ9a15bToCjstd5yO), the png will be updated even if the diagram file doesn't change, so testing the png will not work. @mbestavros and I were also wondering if it makes sense to include this GHA as a [modular test](https://github.com/mbestavros/enarx-modular-tests) instead of including it with this PR.

**Comment by lkatalin** [comment]
@npmccallum We had decided that the GitHub Actions test should be done in a separate PR.

**Comment by lkatalin** [comment]
Closes https://github.com/enarx/enarx/issues/915

**Review by connorkuehl — APPROVED** [review]

**Review by mbestavros — APPROVED** [review]

**Review by npmccallum — APPROVED** [review]

**Pull request merged**
